# generated by Neptune Namespaces v3.x.x
# file: tests/Caffeine.Script.Compatibility.Test/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Caffeine.Script.Compatibility.Test', class Test extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
